version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"